name: Deploy

on: 
  push:
    branches: [week4]

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml


  build:
    needs: [checks]
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.build-push.outputs.app_version }}
    strategy:
      fail-fast: false
      matrix:
        service: [back, front]

        include:
          - service: front
            vite-api-url: ${{ vars.VITE_API_URL }}


    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build and push ${{ matrix.service }} image
        id: build-push
        env: 
          DOCKERHUB_USERNAME: ${{ vars.DOCKER_USER }}
          APP_VERSION: sha-${{ github.sha }}
          LATEST_TAG: latest
        run: |
          docker build \
          --build-arg VITE_API_URL=${{ matrix.vite-api-url }} \
          -t ${{ vars.DOCKER_USER }}/todo-${{ matrix.service }}:${APP_VERSION} \
          -t ${{ vars.DOCKER_USER }}/todo-${{ matrix.service }}:${LATEST_TAG} \
          ./${{ matrix.service }}

          docker push ${{ vars.DOCKER_USER }}/todo-${{ matrix.service }}:${APP_VERSION}
          docker push ${{ vars.DOCKER_USER }}/todo-${{ matrix.service }}:${LATEST_TAG}
          # Передаём SHA образов в output, чтобы не дублировать в deploy
          echo "app_version=$APP_VERSION" >> "$GITHUB_OUTPUT"
  

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                  cd /var/www/it-incubator-app
                  sed -i "s|^APP_VERSION=.*|APP_VERSION=${{ needs.build.outputs.app_version }}|" .env.development.compose
                  docker compose --env-file .env.development.compose pull
                  docker compose --env-file .env.development.compose up -d --no-deps front back

